### ISSUE TITLE
Posting ShowDetails, Delete 기능 구현

### ISSUE THREAD

**Issue by JeekLee** [m1naworld/hanghae-instagram-api#43]
## Description
Posting Show 기능 구현(Like Domain과 연동)

## Todo
- [x] Member JSON Mock data 변경
- [x] Column 생성 시 Default 설정
- [x] 생성 및 수정 날짜 반환 로직 수정
- [x] 좋아요 숫자 반환 기능 구현

## Etc
기타사항
